import { IUser } from "../../interfaces/user";

export const data: Array<IUser> = [
  {
    id: 1,
    name: "root",
    password: "root",
    email: "root@softplan.com",
    isActive: true,
    role: "ADMIN",
    job: "CTO",
  },
  {
    id: 2,
    name: "Arlino",
    password: "initial",
    email: "arlino@softplan.com",
    isActive: true,
    role: "USER",
    job: "Developer",
  },
  {
    id: 3,
    name: "Sarah",
    password: "initial",
    email: "sarah@softplan.com",
    isActive: true,
    role: "USER",
    job: "Product Designer",
  },
  {
    id: 4,
    name: "Alanaa",
    password: "initial",
    email: "alana@softplan.com",
    isActive: true,
    role: "USER",
    job: "Marketing",
  },
  {
    id: 5,
    name: "André",
    password: "initial",
    email: "andre@softplan.com",
    isActive: false,
    role: "USER",
    job: "Data Science",
  },
  {
    id: 6,
    name: "Marcos",
    password: "initial",
    email: "marcos@softplan.com",
    isActive: true,
    role: "USER",
    job: "Support",
  },
];
